Project 5: Styling
sarazaToussaint/Book-Store pull request #5
Opened 2022-06-16 18:27 UTC by sarazaToussaint

### In this pull request we:

- Design the Bookstore website based on [Zeplin](https://zeplin.io/)

2022-06-16 19:00 UTC, hiromataba requested changes
Hi @sarazaToussaint     :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your PR has a proper title and description  :+1: 
- Your linters are passing :heavy_check_mark:  
- Profesional README file :rocket: 

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-16 19:00 UTC, hiromataba commented on src/components/Interface/AddBook.module.css
> +
- [ ] Please style your dropdown to select the category to look like the original design and the color of your `ADD NEW BOOK` title

Your design 👇 

![image](https://user-images.githubusercontent.com/75126481/174143562-7c3b1f9a-fff1-43bc-afe3-d4a0cc3d11e2.png)

Original design 👇 

![image](https://user-images.githubusercontent.com/75126481/174143975-c1fa75d5-5cea-424f-8ca0-9c6990faa25a.png)

2022-06-16 19:00 UTC, hiromataba commented on src/components/Book.module.css
> +
- [x] Please update your navbar by adding the user icon and the colors

Your design 👇 

![image](https://user-images.githubusercontent.com/75126481/174144285-1bcd59f4-b441-4317-af85-8f90c5ea5882.png)

Zeplin Design 👇 

![image](https://user-images.githubusercontent.com/75126481/174144428-1f767b85-5b52-44f6-bbfc-f7b6b156b27a.png)

2022-06-16 19:00 UTC, hiromataba commented on src/components/Book.module.css
> +.book {
- [ ] Please add the section showing the percentage and the current chapter as well, because now your design does not have it so please try to update that and double-check the colors and font please

Your design 👇 

![image](https://user-images.githubusercontent.com/75126481/174145064-1f81bb97-d291-4eda-adca-5283284a83f2.png)

Zeplin design 👇 

![image](https://user-images.githubusercontent.com/75126481/174144874-75fdb55d-179a-4600-bc91-b07bd70a427a.png)

2022-06-18 14:45 UTC, ShoiraTa approved these changes
## **STATUS: APPROVED  🟢 ** 
------
### Hi @sarazaToussaint , 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-18 15:01 UTC, sarazaToussaint commented
Thank you for approval @ShoiraTa

2022-06-18 15:02 UTC, merged

2023-06-07 13:28 UTC, sarazaToussaint commented on src/components/Book.module.css
> +.book {
Hi @hiromataba, thank you for the code review.